### ISSUE TITLE
outdated dependency

### ISSUE THREAD

**Issue by mehreencs87** [auth0/auth0-vanillajs-api-sample#15]
bootstrap.min.css 3.3.6 --> 3.3.7

**Comment by mehreencs87** [comment]
fix here https://github.com/auth0/auth0-vanillajs-api-sample/pull/16

**Comment by mpaktiti** [comment]
The sample has been moved to https://github.com/auth0-samples/auth0-javascript-spa some time ago, and the doc has been update to reflect it https://auth0.com/docs/quickstart/spa/vanillajs/01-login

Also, it looks like the particular dependency has been removed from the sample altogether so I will close this issue.
